// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZyxdnenEmZrRjgG4PB_nn7fHANqqkHk',
    appId: '1:103962969762:web:e0541b673774b391eeb9fb',
    messagingSenderId: '103962969762',
    projectId: 'doctorapp3b',
    authDomain: 'doctorapp3b.firebaseapp.com',
    storageBucket: 'doctorapp3b.firebasestorage.app',
    measurementId: 'G-6S397XZ7HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChSx4SqEi3e13bKz7l1gs8VsnPVfERGZ4',
    appId: '1:103962969762:android:e748ffc6e6963c4deeb9fb',
    messagingSenderId: '103962969762',
    projectId: 'doctorapp3b',
    storageBucket: 'doctorapp3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHUikFqZx11C_EBpDPXVVaDt3yJ95KPnw',
    appId: '1:103962969762:ios:9bbd1401a6561e64eeb9fb',
    messagingSenderId: '103962969762',
    projectId: 'doctorapp3b',
    storageBucket: 'doctorapp3b.firebasestorage.app',
    iosBundleId: 'com.example.actividad3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHUikFqZx11C_EBpDPXVVaDt3yJ95KPnw',
    appId: '1:103962969762:ios:9bbd1401a6561e64eeb9fb',
    messagingSenderId: '103962969762',
    projectId: 'doctorapp3b',
    storageBucket: 'doctorapp3b.firebasestorage.app',
    iosBundleId: 'com.example.actividad3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgZyxdnenEmZrRjgG4PB_nn7fHANqqkHk',
    appId: '1:103962969762:web:c67604d7745f37f4eeb9fb',
    messagingSenderId: '103962969762',
    projectId: 'doctorapp3b',
    authDomain: 'doctorapp3b.firebaseapp.com',
    storageBucket: 'doctorapp3b.firebasestorage.app',
    measurementId: 'G-TKL891B144',
  );
}
